# Generated by Django 3.0.7 on 2021-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.png', null=True, upload_to='posts'),
        ),
    ]
